services:
    chromadb:
        image: 'chromadb/chroma:0.5.15'
        ports:
            - '8080:8000'
        volumes:
            - chroma-data:/chroma/chroma
        environment:
            - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["http://localhost:8090"]
volumes:
    chroma-data:
        driver: local
